//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouTube.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YouTube.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap About_logo {
            get {
                object obj = ResourceManager.GetObject("About_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddToList {
            get {
                object obj = ResourceManager.GetObject("AddToList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!&lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=8&quot; /&gt;
        ///	&lt;title&gt;Browse Error&lt;/title&gt;
        ///	&lt;link rel=&quot;stylesheet&quot; href=&quot;__cssfile__&quot; /&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body class=&quot;browsePage&quot;&gt;
        ///
        ///	&lt;div id=&quot;browseError&quot;&gt;
        ///		&lt;span id=&quot;browseErrorText&quot;&gt;__error_text__&lt;/span&gt;
        ///		&lt;span class=&quot;verticalAlign&quot;&gt;&lt;/span&gt;
        ///	&lt;/div&gt;
        ///
        ///&lt;/body&gt;
        ///
        ///&lt;/html&gt;.
        /// </summary>
        internal static string browseError {
            get {
                return ResourceManager.GetString("browseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BrowseHeader {
            get {
                object obj = ResourceManager.GetObject("BrowseHeader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BrowseHeaderLogo {
            get {
                object obj = ResourceManager.GetObject("BrowseHeaderLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!&lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=8&quot; /&gt;
        ///	&lt;title&gt;Browse results&lt;/title&gt;
        ///	&lt;link rel=&quot;stylesheet&quot; href=&quot;__cssfile__&quot; /&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body class=&quot;browsePage&quot;&gt;
        ///	
        ///	&lt;div class=&quot;browseResultsBox&quot;&gt;
        ///
        ///		&lt;p id=&quot;browseStatusText&quot;&gt;__status__&lt;/p&gt;
        ///
        ///		&lt;div id=&quot;browseResultsItems&quot;&gt;
        ///		&lt;/div&gt;
        ///
        ///		&lt;div id=&quot;browseResultsMore&quot; class=&quot;hidden&quot;&gt;
        ///			&lt;a href=&quot;javascript:window.external.ActionClick(&apos;loadMore&apos;,&apos;&apos;)&quot;&gt;Load more videos&lt;/a&gt;
        ///		&lt;/div&gt;
        ///
        ///	&lt;/div&gt;
        ///	&lt;div id=&quot;loading&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string browseResults {
            get {
                return ResourceManager.GetString("browseResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;videoItem&quot;&gt;
        ///	&lt;div class=&quot;thumbnail&quot;&gt;
        ///		&lt;img src=&quot;__thumbnail__&quot; /&gt;
        ///		&lt;span class=&quot;videoDuration&quot;&gt;__duration__&lt;/span&gt;
        ///	&lt;/div&gt;
        ///	&lt;div class=&quot;videoTitle&quot;&gt;&lt;a href=&quot;javascript:window.external.VideoClick(__index__,&apos;title&apos;)&quot; title=&quot;__title__&quot;&gt;__title__&lt;/a&gt;&lt;/div&gt;
        ///	&lt;div class=&quot;videoDescription&quot;&gt;__description__&lt;/div&gt;
        ///	&lt;div class=&quot;videoInfo&quot;&gt;By &lt;a href=&quot;javascript:window.external.VideoClick(__index__,&apos;author&apos;)&quot;&gt;__author__&lt;/a&gt; | __viewcount__ views | __upload_date__&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string browseResultsItem {
            get {
                return ResourceManager.GetString("browseResultsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BrowseToWatch {
            get {
                object obj = ResourceManager.GetObject("BrowseToWatch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BrowseToWatch_Disabled {
            get {
                object obj = ResourceManager.GetObject("BrowseToWatch_Disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BrowseToWatch_Hover {
            get {
                object obj = ResourceManager.GetObject("BrowseToWatch_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BrowseToWatch_Pressed {
            get {
                object obj = ResourceManager.GetObject("BrowseToWatch_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!&lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=8&quot; /&gt;
        ///	&lt;title&gt;Guide&lt;/title&gt;
        ///	&lt;link rel=&quot;stylesheet&quot; href=&quot;__cssfile__&quot; /&gt;
        ///	&lt;script&gt;
        ///		function SelectFeed(name) {
        ///			var anchors = document.getElementsByTagName(&apos;a&apos;);
        ///			for (var i=0; i &lt; anchors.length; i++) {
        ///				anchors[i].className = &quot;&quot;;
        ///			}
        ///
        ///			var selAnchor = document.getElementById(name);
        ///			
        ///			if (selAnchor) {
        ///				selAnchor.className = &quot;selected&quot;;
        ///				window.external.ActionClick(&apos;selectFeed&apos;, name);        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string guide {
            get {
                return ResourceManager.GetString("guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerButton_Hover {
            get {
                object obj = ResourceManager.GetObject("PlayerButton_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerButton_Normal {
            get {
                object obj = ResourceManager.GetObject("PlayerButton_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerButton_Pressed {
            get {
                object obj = ResourceManager.GetObject("PlayerButton_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerControlsBack {
            get {
                object obj = ResourceManager.GetObject("PlayerControlsBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerExitFullscreen {
            get {
                object obj = ResourceManager.GetObject("PlayerExitFullscreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerExitFullscreen_Hover {
            get {
                object obj = ResourceManager.GetObject("PlayerExitFullscreen_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerFullscreen {
            get {
                object obj = ResourceManager.GetObject("PlayerFullscreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerFullscreen_Hover {
            get {
                object obj = ResourceManager.GetObject("PlayerFullscreen_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerLarge {
            get {
                object obj = ResourceManager.GetObject("PlayerLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerLarge_Hover {
            get {
                object obj = ResourceManager.GetObject("PlayerLarge_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerMute {
            get {
                object obj = ResourceManager.GetObject("PlayerMute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerMute_Hover {
            get {
                object obj = ResourceManager.GetObject("PlayerMute_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerNormal {
            get {
                object obj = ResourceManager.GetObject("PlayerNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerNormal_Hover {
            get {
                object obj = ResourceManager.GetObject("PlayerNormal_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerPause {
            get {
                object obj = ResourceManager.GetObject("PlayerPause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerPause_Hover {
            get {
                object obj = ResourceManager.GetObject("PlayerPause_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerPlay {
            get {
                object obj = ResourceManager.GetObject("PlayerPlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerPlay_Hover {
            get {
                object obj = ResourceManager.GetObject("PlayerPlay_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerVolumeMax {
            get {
                object obj = ResourceManager.GetObject("PlayerVolumeMax", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerVolumeMax_Hover {
            get {
                object obj = ResourceManager.GetObject("PlayerVolumeMax_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerVolumeMed {
            get {
                object obj = ResourceManager.GetObject("PlayerVolumeMed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerVolumeMed_Hover {
            get {
                object obj = ResourceManager.GetObject("PlayerVolumeMed_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerVolumeMin {
            get {
                object obj = ResourceManager.GetObject("PlayerVolumeMin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerVolumeMin_Hover {
            get {
                object obj = ResourceManager.GetObject("PlayerVolumeMin_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PopupHeader {
            get {
                object obj = ResourceManager.GetObject("PopupHeader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SearchBoxText {
            get {
                object obj = ResourceManager.GetObject("SearchBoxText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SearchButton_Disabled {
            get {
                object obj = ResourceManager.GetObject("SearchButton_Disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SearchButton_Hover {
            get {
                object obj = ResourceManager.GetObject("SearchButton_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SearchButton_Normal {
            get {
                object obj = ResourceManager.GetObject("SearchButton_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SearchButton_Pressed {
            get {
                object obj = ResourceManager.GetObject("SearchButton_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SeekBar_Buffer {
            get {
                object obj = ResourceManager.GetObject("SeekBar_Buffer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SeekBar_Fill {
            get {
                object obj = ResourceManager.GetObject("SeekBar_Fill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SeekBar_Track {
            get {
                object obj = ResourceManager.GetObject("SeekBar_Track", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SeekBarThumb_Hover {
            get {
                object obj = ResourceManager.GetObject("SeekBarThumb_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SeekBarThumb_Normal {
            get {
                object obj = ResourceManager.GetObject("SeekBarThumb_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SeekBarThumb_Pressed {
            get {
                object obj = ResourceManager.GetObject("SeekBarThumb_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SettingsDark {
            get {
                object obj = ResourceManager.GetObject("SettingsDark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SettingsDark_Hover {
            get {
                object obj = ResourceManager.GetObject("SettingsDark_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SettingsDark_Pressed {
            get {
                object obj = ResourceManager.GetObject("SettingsDark_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SettingsLight {
            get {
                object obj = ResourceManager.GetObject("SettingsLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SettingsLight_Hover {
            get {
                object obj = ResourceManager.GetObject("SettingsLight_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SettingsLight_Pressed {
            get {
                object obj = ResourceManager.GetObject("SettingsLight_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!&lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=8&quot; /&gt;
        ///	&lt;title&gt;Video Cover&lt;/title&gt;
        ///	&lt;link rel=&quot;stylesheet&quot; href=&quot;__cssfile__&quot; /&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body class=&quot;videoCover&quot; onclick=&quot;window.external.ActionClick(&apos;videoCover&apos;, &apos;focusControls&apos;)&quot;&gt;
        ///	&lt;div id=&quot;cover&quot;&gt;
        ///		&lt;img src=&quot;__thumbnailHQ__&quot; id=&quot;videoThumb&quot; 
        ///		/&gt;&lt;span class=&quot;verticalAlign&quot;&gt;&lt;/span&gt;
        ///	&lt;/div&gt;
        ///
        ///	&lt;div id=&quot;startScreen&quot; class=&quot;overlay&quot;&gt;
        ///		&lt;a id=&quot;playBtn&quot; href=&quot;javascript:window.external.ActionClick(&apos;videoCover&apos;, &apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string videoCover {
            get {
                return ResourceManager.GetString("videoCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!&lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=8&quot; /&gt;
        ///	&lt;title&gt;Video Description&lt;/title&gt;
        ///	&lt;link rel=&quot;stylesheet&quot; href=&quot;__cssfile__&quot; /&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body class=&quot;videoDescriptionPanel&quot;&gt;
        ///	&lt;div id=&quot;description&quot;&gt;
        ///		&lt;div id=&quot;videoTitle&quot;&gt;__title__&lt;/div&gt;
        ///		&lt;div id=&quot;videoMeta&quot;&gt;
        ///			&lt;span class=&quot;rating r3 half&quot;&gt;&lt;/span&gt;
        ///			Posted by
        ///			&lt;a href=&quot;javascript:window.external.VideoClick(-1, &apos;author&apos;)&quot;&gt;__author__&lt;/a&gt;
        ///			&amp;bull;
        ///			&lt;span&gt;__upload_date__&lt;/span&gt;
        ///			&amp;bull;
        ///			&lt;span&gt;_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string videoDescription {
            get {
                return ResourceManager.GetString("videoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;videoItem&quot;&gt;
        ///	&lt;div class=&quot;thumbnail&quot;&gt;
        ///		&lt;img src=&quot;__thumbnail__&quot; /&gt;
        ///		&lt;span class=&quot;videoDuration&quot;&gt;__duration__&lt;/span&gt;
        ///	&lt;/div&gt;
        ///	&lt;div class=&quot;videoTitle&quot;&gt;&lt;a href=&quot;javascript:window.external.VideoClick(__index__,&apos;title&apos;)&quot; title=&quot;__title__&quot;&gt;__title__&lt;/a&gt;&lt;/div&gt;
        ///	&lt;div class=&quot;videoAuthor&quot;&gt;By &lt;a href=&quot;javascript:window.external.VideoClick(__index__,&apos;author&apos;)&quot;&gt;__author__&lt;/a&gt;&lt;/div&gt;
        ///	&lt;div class=&quot;videoInfo&quot;&gt;__viewcount__ &amp;bull; __upload_date__&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string videoItem {
            get {
                return ResourceManager.GetString("videoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!&lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=8&quot; /&gt;
        ///	&lt;title&gt;Related videos&lt;/title&gt;
        ///	&lt;link rel=&quot;stylesheet&quot; href=&quot;__cssfile__&quot; /&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body class=&quot;videoRelated&quot;&gt;
        ///	&lt;p&gt;Related videos&lt;/p&gt;
        ///
        ///	&lt;div id=&quot;relatedItems&quot;&gt;
        ///	&lt;/div&gt;
        ///
        ///	&lt;div id=&quot;loading&quot;&gt;&lt;/div&gt;
        ///&lt;/body&gt;
        ///
        ///&lt;/html&gt;.
        /// </summary>
        internal static string videoRelated {
            get {
                return ResourceManager.GetString("videoRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WatchHeader {
            get {
                object obj = ResourceManager.GetObject("WatchHeader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WatchHeaderLogo {
            get {
                object obj = ResourceManager.GetObject("WatchHeaderLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WatchToBrowse {
            get {
                object obj = ResourceManager.GetObject("WatchToBrowse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WatchToBrowse_Disabled {
            get {
                object obj = ResourceManager.GetObject("WatchToBrowse_Disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WatchToBrowse_Hover {
            get {
                object obj = ResourceManager.GetObject("WatchToBrowse_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WatchToBrowse_Pressed {
            get {
                object obj = ResourceManager.GetObject("WatchToBrowse_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WatchVideoLarge {
            get {
                object obj = ResourceManager.GetObject("WatchVideoLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WatchVideoLarge_Disabled {
            get {
                object obj = ResourceManager.GetObject("WatchVideoLarge_Disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WatchVideoLarge_Hover {
            get {
                object obj = ResourceManager.GetObject("WatchVideoLarge_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WatchVideoLarge_Pressed {
            get {
                object obj = ResourceManager.GetObject("WatchVideoLarge_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WatchVideoNormal {
            get {
                object obj = ResourceManager.GetObject("WatchVideoNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WatchVideoNormal_Disabled {
            get {
                object obj = ResourceManager.GetObject("WatchVideoNormal_Disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WatchVideoNormal_Hover {
            get {
                object obj = ResourceManager.GetObject("WatchVideoNormal_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WatchVideoNormal_Pressed {
            get {
                object obj = ResourceManager.GetObject("WatchVideoNormal_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
